### ISSUE TITLE
Use bot commands instead of looking for commands in on_message

### ISSUE THREAD

**Issue by DonChalupa** [DonChalupa/Robbot#2]
https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html

Only glimpsed at this, but seems like a much cleaner way to organize commands. Abstracts away the code that checks each message for commands, allows us to contain each command's functionality in its own function, and allows us to nest commands or reuse them.

**Comment by MonkfishFillet** [comment]
I like this. We'll need a standard for how we want the arguments to be passed in on client-side. The docs say quotes are used for spaced-out args, but I think we should join them together server-side to make it cleaner. Quotes are cringe.

**Comment by DonChalupa** [comment]
Starting work on this. Kinda weird that you can't create a tracked branch from issues like you can in JIRA

**Comment by DonChalupa** [comment]
> 
> 
> I like this. We'll need a standard for how we want the arguments to be passed in on client-side. The docs say quotes are used for spaced-out args, but I think we should join them together server-side to make it cleaner. Quotes are cringe.

Yeah, in general I think we'll use the keyword arg style they describe in there, although it will vary from case to case. I don't want the user to wrap their stuff in quotes.
